### PR TITLE
Fix for issue #12 escape sharp

### PR DESCRIPTION
**Pull request by marklister**
I had to clean up some "fixing" that intelliJ did for me.

### CODE REVIEW

**Comment by marklister** [comment]
The last commit widens the search for templates to unmanaged sources, which I needed in a cross compiled scala-js project.

**Comment by jrudolph** [comment]
@marklister sorry for letting this lie around for years. I have "remixed" your commits a bit and will merge something soon.

"Search unmanaged sources for templates too" doesn't seem to work for me. At least it changes the semantics from before because it doesn't include the `boilerplate` directory any more, right?

Anyway, we should make this a separate change if needed.

**Comment by jrudolph** [comment]
I merged most of this but the "Search unmanaged sources for templates too" commit so far.

Thanks again, @marklister!

**Comment by marklister** [comment]
Thanks!  I'll test it against product-collections and file issues for anything remaining.

**Pull request closed without merging**
